import { FormEvent, useMemo, useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, Clipboard, ExternalLink, Github, ShieldCheck } from 'lucide-react';
import { Header, Footer } from '../components/nexus-site';
type Route='/method'|'/systems'|'/work'|'/proof'|'/about'|'/contact';
const meta:Record<Route,[string,string]>={
  '/method':['01','METHOD / FROM INTENT TO EVIDENCE'],
  '/systems':['02','SYSTEMS / SURFACES WITH A PURPOSE'],
  '/work':['03','WORK / SELECTED PUBLIC ARTIFACTS'],
  '/proof':['04','PROOF / CLAIMS WITH BOUNDARIES'],
  '/about':['05','ABOUT / OPERATING PRINCIPLES'],
  '/contact':['06','START / TURN A PROBLEM INTO A BRIEF'],
};
function Shell({route,children}:{route:Route;children:React.ReactNode}){const m=meta[route];return <><a className="skip-link" href="#main">Skip to content</a><Header/><main id="main" className="section-shell" style={{minHeight:'70vh',paddingTop:32,paddingBottom:100}}><div style={{display:'flex',justifyContent:'space-between',paddingBottom:18,borderBottom:'1px solid var(--subtle-line)',color:'var(--muted-foreground)',font:'500 10px var(--font-code)',letterSpacing:'.08em'}}><span>{m[1]}</span><span style={{color:'var(--primary)'}}>NXS / {m[0]}</span></div>{children}</main><Footer/></>;}
function Intro({route,title,copy}:{route:Route;title:React.ReactNode;copy:string}){return <header style={{display:'grid',gridTemplateColumns:'.7fr 2fr 1fr',gap:48,padding:'76px 0 82px',borderBottom:'1px solid var(--subtle-line)'}}><span style={{color:'var(--muted-foreground)',font:'500 10px var(--font-code)'}}>{meta[route][1]}</span><h1 style={{margin:0,fontSize:'clamp(48px,7vw,104px)',lineHeight:.94,letterSpacing:'-.055em'}}>{title}</h1><p style={{alignSelf:'end',margin:0,color:'var(--muted-foreground)',fontSize:17,lineHeight:1.7}}>{copy}</p></header>;}
function Method(){const x=[['01','Direction','Decision record','Define outcome, audience, constraints, and thesis.'],['02','System','Interface contract','Turn the thesis into reusable components, routes, content, and states.'],['03','Proof','Evidence trail','Verify behavior, accessibility, recovery, and deployment.'],['04','Frontier','Next horizon','Record open gates and preserve an evolution path.']];return <Shell route="/method"><Intro route="/method" title={<>A site should<br/>behave like a <span>system.</span></>} copy="A coherent public surface must let navigation, content, interactions, evidence boundaries, and evolution be inspected."/><section style={{paddingTop:64}}>{x.map(r=><article key={r[0]} style={{display:'grid',gridTemplateColumns:'55px 1fr 1.5fr 160px',gap:18,padding:'24px 0',borderBottom:'1px solid var(--subtle-line)'}}><span style={{color:'var(--primary)',font:'600 10px var(--font-code)'}}>/{r[0]}</span><div><h2 style={{margin:0,fontSize:34}}>{r[1]}</h2><span style={{color:'var(--primary)',font:'500 9px var(--font-code)'}}>{r[2]}</span></div><p style={{margin:0,color:'var(--muted-foreground)',lineHeight:1.7}}>{r[3]}</p><span style={{color:'var(--muted-foreground)',font:'500 9px var(--font-code)'}}>OUTPUT / {r[2]}</span></article>)}</section></Shell>;}
function Systems(){const x=[['01','Control Plane','State, decisions, health, operational context.'],['02','Graph Explorer','Relationships, provenance, dependencies, propagation.'],['03','Local Layer','Inspection, verification, recovery, ownership.']];return <Shell route="/systems"><Intro route="/systems" title={<>Interfaces are<br/><span>surfaces over structure.</span></>} copy="The interface is the visible edge of a larger system: content, state, relationships, evidence, recovery, and maintainable tooling."/><section style={{paddingTop:64}}><div className="systems-grid">{x.map(r=><article className="system-card" key={r[0]}><div className="system-card-heading"><span>{r[0]}</span><span>REFERENCE</span></div><div className="system-card-copy"><h3>{r[1]}</h3><p>{r[2]}</p></div></article>)}</div></section><section style={{paddingTop:64}}><div className="section-intro"><span className="section-label">RELATION MODEL</span><h2>Intent → Design → Build → Run → Observe → <span>Verify.</span></h2></div></section></Shell>;}
function Work(){const x=[['01','LLM MCP Android','PUBLIC SYSTEM / RUNTIME','https://github.com/Loofy147/Llms-mcp-android'],['02','Open System One','PUBLIC RESEARCH / DECISION SUBSTRATE','https://github.com/Loofy147/Open-System-One'],['03','Client Proof','PUBLIC EVIDENCE SURFACE','https://github.com/Loofy147/client-proof']];return <Shell route="/work"><Intro route="/work" title={<>Show the work.<br/>Show the <span>limits.</span></>} copy="Selected public repositories and evidence surfaces, with their boundaries kept visible."/><section style={{paddingTop:64}}>{x.map(r=><article key={r[0]} style={{display:'grid',gridTemplateColumns:'55px 1fr 180px 24px',gap:18,padding:'24px 0',borderBottom:'1px solid var(--subtle-line)',alignItems:'center'}}><span className="nexus-id">{r[0]}</span><h2 style={{margin:0,fontSize:32}}>{r[1]}</h2><span style={{color:'var(--primary)',font:'500 9px var(--font-code)'}}>{r[2]}</span><a href={r[3]} target="_blank" rel="noreferrer"><ExternalLink size={15}/></a></article>)}</section></Shell>;}
function Proof(){const x=[['MCP-REST-001','MCP → REST Integration','PORTFOLIO PROOF'],['API-INTEGRATION-001','Webhook → REST Integration','EXPERIMENTALLY SUPPORTED'],['WORKFLOW-001','Verified Workflow Conversion','EXPERIMENTALLY SUPPORTED'],['AGENT-RUNTIME-001','Bounded Agent Runtime','EXPERIMENTALLY SUPPORTED']];return <Shell route="/proof"><Intro route="/proof" title={<>Trust comes from<br/><span>inspectable boundaries.</span></>} copy="The public proof standard makes problem, outcome, implementation, verification, evidence, limits, and commercial mapping visible."/><section style={{paddingTop:64}}>{x.map(r=><article key={r[0]} style={{display:'grid',gridTemplateColumns:'190px 1fr 22px',gap:20,padding:'20px 0',borderBottom:'1px solid var(--subtle-line)'}}><span className="nexus-id">{r[0]}</span><div><h2 style={{margin:0,fontSize:24}}>{r[1]}</h2><span style={{color:'var(--primary)',font:'600 10px var(--font-code)'}}>{r[2]}</span></div><ShieldCheck size={15}/></article>)}</section></Shell>;}
function About(){const x=[['01','Machine-native first','Expose real capabilities rather than imitate a human workflow.'],['02','Evidence before confidence','Claims carry status, provenance, and limits.'],['03','Replaceable providers','Contracts survive provider changes.'],['04','Evolution over ornament','New surfaces earn their place through capability or decision value.']];return <Shell route="/about"><Intro route="/about" title={<>Build interfaces<br/>worth <span>remembering.</span></>} copy="NEXUS is a working direction for premium interface systems: visual point of view, explicit architecture, disciplined evidence, and room to evolve."/><section style={{paddingTop:64}}><div className="systems-grid">{x.map(r=><article className="system-card" key={r[0]}><div className="system-card-copy"><span className="nexus-id">{r[0]}</span><h3>{r[1]}</h3><p>{r[2]}</p></div></article>)}</div></section></Shell>;}
function Contact(){const [f,setF]=useState({name:'',problem:'',system:'',outcome:''});const [ready,setReady]=useState(false);const [copied,setCopied]=useState(false);const brief=useMemo(()=>['NEXUS INQUIRY','Name: '+(f.name||'Not provided'),'Problem: '+(f.problem||'Not provided'),'Current system: '+(f.system||'Not provided'),'Desired outcome: '+(f.outcome||'Not provided')].join('\n'),[f]);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setReady(true);setCopied(false)};const copy=async()=>{try{await navigator.clipboard.writeText(brief);setCopied(true)}catch{}};return <Shell route="/contact"><Intro route="/contact" title={<>Bring a problem.<br/>Leave with a <span>brief.</span></>} copy="This is a local inquiry brief generator. It does not pretend to be a backend CRM or submission endpoint."/><section style={{paddingTop:64}}><div className="systems-grid"><form className="system-card" onSubmit={submit}><div className="system-card-copy"><span className="nexus-tag">INQUIRY / LOCAL ONLY</span>{(['name','problem','system','outcome'] as const).map(k=><label key={k} style={{display:'grid',gap:7,marginTop:18,font:'500 10px var(--font-code)',textTransform:'uppercase'}}>{k==='name'?'Name':k==='problem'?'Problem':k==='system'?'Current system':'Desired outcome'}{k==='name'?<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/>:<textarea required={k==='problem'||k==='outcome'} rows={4} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>}</label>)}<button className="btn btn-nexus btn-size-nexus" style={{marginTop:20}} type="submit">Generate inquiry brief <ArrowUpRight size={15}/></button></div></form><aside className="system-card"><div className="system-card-copy"><span className="nexus-tag">{ready?'READY':'WAITING'}</span><div style={{minHeight:280,marginTop:18,padding:16,border:'1px solid var(--subtle-line)',background:'var(--surface-deep)'}}><pre style={{whiteSpace:'pre-wrap',font:'12px/1.7 var(--font-code)',color:'var(--muted-foreground)'}}>{ready?brief:'Your structured brief will appear here.'}</pre></div><button className="btn btn-nexusOutline btn-size-nexus" disabled={!ready} type="button" onClick={copy} style={{marginTop:18}}><Clipboard size={15}/>{copied?'Copied':'Copy brief'}</button><a className="text-link" href="https://github.com/Loofy147/client-proof" target="_blank" rel="noreferrer"><Github size={14}/> Proof standard</a></div></aside></div></section></Shell>;}
export function SitePage({route}:{route:Route}){switch(route){case '/method':return <Method/>;case '/systems':return <Systems/>;case '/work':return <Work/>;case '/proof':return <Proof/>;case '/about':return <About/>;case '/contact':return <Contact/>;}}
